return {
  'lmantw/themify.nvim',
  lazy = false,
  priority = 1000,
  config = {
    'Abstract-IDE/Abstract-cs',
    'AlessandroYorba/Alduin',
    'AlexvZyl/nordic.nvim',
    'DeviusVim/deviuspro.nvim',
    'EdenEast/nightfox.nvim',
    'HoNamDuong/hybrid.nvim',
    'Mofiqul/adwaita.nvim',
    'Mofiqul/dracula.nvim',
    'Mofiqul/vscode.nvim',
    'NLKNguyen/papercolor-theme',
    'Shatur/neovim-ayu',
    'TaurusOlson/creature.vim',
    'Yazeed1s/oh-lucy.nvim',
    'Verf/deepwhite.nvim',
    'aliqyan-21/darkvoid.nvim',
    'armannikoyan/rusty',
    'ashish2508/Eezzy.nvim',
    'baliestri/aura-theme',
    'bdesham/biogoo',
    'blueshirts/darcula',
    'bluz71/vim-moonfly-colors',
    'brafales/vim-desert256',
    'catppuccin/nvim',
    'craftzdog/solarized-osaka.nvim',
    'crusoexia/vim-monokai',
    {
      'datsfilipe/vesper.nvim',
      before = function(theme)
        require('vesper').setup({
          italics = {
            comments = false,
            keywords = false,
            functions = false,
            strings = false,
            variables = false,
          },
        })
      end,
    },
    'ellisonleao/gruvbox.nvim',
    'evgenyzinoviev/vim-vendetta',
    'ficcdaf/ashen.nvim',
    'folke/tokyonight.nvim',
    'jalvesaq/southernlights',
    'keiyakeiya/PapilioDehaanii.vim',
    'kepano/flexoki',
    'logico/typewriter',
    'ntk148v/slack.nvim',
    'nxvu699134/vn-night.nvim',
    'olivercederborg/poimandres.nvim',
    'pauchiner/pastelnight.nvim',
    'pmouraguedes/neodarcula.nvim',
    'ramojus/mellifluous.nvim',
    'rebelot/kanagawa.nvim',
    'rockyzhang24/arctic.nvim',
    'rose-pine/neovim',
    'sainnhe/gruvbox-material',
    'sainnhe/sonokai',
    'sam4llis/nvim-tundra',
    'shaunsingh/nord.nvim',
    'strange/strange.vim',
    'thesimonho/kanagawa-paper.nvim',
    'tiesen243/vercel.nvim',
    'vim-scripts/DarkZen-Color-Scheme',
    'vim-scripts/Darkdevel',
    'wesleimp/min-theme.nvim',
    'xiantang/darcula-dark.nvim',
    'yorik1984/newpaper.nvim',
  },
  keys = {
    { '<leader>mc', ':Themify<cr>', desc = 'Color schemes' },
  },
}
