return {
  'lmantw/themify.nvim',
  lazy = false,
  priority = 1000,
  config = {
    'AlessandroYorba/Alduin',
    'armannikoyan/rusty',
    'bdesham/biogoo',
    'brafales/vim-desert256',
    'EdenEast/nightfox.nvim',
    'Mofiqul/vscode.nvim',
    'crusoexia/vim-monokai',
    'datsfilipe/vesper.nvim',
    'HoNamDuong/hybrid.nvim',
    'folke/tokyonight.nvim',
    'logico/typewriter',
    'morhetz/gruvbox',
    'NLKNguyen/papercolor-theme',
    'rebelot/kanagawa.nvim',
    'rockyzhang24/arctic.nvim',
    'sainnhe/gruvbox-material',
    'sainnhe/sonokai',
    'vim-scripts/DarkZen-Color-Scheme',
    'wesleimp/min-theme.nvim',
    'xiantang/darcula-dark.nvim',
  },
  keys = {
    { '<leader>mc', ':Themify<cr>', desc = 'Color schemes' },
  },
}
