return {
  'lmantw/themify.nvim',
  lazy = false,
  priority = 1000,
  config = {
    'AlessandroYorba/Alduin',
    'EdenEast/nightfox.nvim',
    'Mofiqul/vscode.nvim',
    'catppuccin/nvim',
    'crusoexia/vim-monokai',
    'doums/darcula',
    'ellisonleao/gruvbox.nvim',
    'folke/tokyonight.nvim',
    'logico/typewriter',
    'morhetz/gruvbox',
    'owickstrom/vim-colors-paramount',
    'projekt0n/github-nvim-theme',
    'rebelot/kanagawa.nvim',
    'rockyzhang24/arctic.nvim',
    'sainnhe/gruvbox-material',
    'wesleimp/min-theme.nvim',
    'xiantang/darcula-dark.nvim',
  },
  keys = {
    { '<leader>mc', ':Themify<cr>', desc = 'Color schemes' },
  },
}
